# Site
name: "Crypto MS"
title: "Divers sujets sur les Blockchains & Crypto-actifs"
description: "Site internet spécialisé autour des technologies Blockchain & crypto-actifs"
meta_description: "Site internet spécialisé autour des technologies Blockchain & crypto-actifs"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/crypto-ms-website/'
email: 'steve.despres@protonmail.com'

# Authors
authors:
  steve:
    name: Steve Despres
    display_name: Steve
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: steve.despres@protonmail.com
    web: https://cryptoms.fr/apropos
    twitter: https://twitter.com/_SteveD
    description: "Développeur & passionné des technologies Blockchain"
  marvin:
    name: Marvin Beaufort
    display_name: Marvin
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: marvin.beaufort@orange.fr
    web: https://cryptoms.fr/apropos
    twitter: 
    description: "Diplômé de Master CCA, passionné d'économie et de crypto-économie"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categorie/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

# Server config
include:
  - _headers

