# Site
name: "CryptoMS"
title: "Divers sujets sur les Blockchains & Crypto-actifs"
description: "Site internet spécialisé autour des technologies Blockchain & crypto-actifs"
meta_description: "Site internet spécialisé autour des technologies Blockchain & crypto-actifs"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
true_url: 'https://cryptoms.fr'
email: 'steve.despres@protonmail.com'

# Authors
authors:
  steve:
    name: Steve Despres
    display_name: Steve
    gravatar: 5acfe966ca013f83ef68213dd2e5ec56
    email: steve.despres@protonmail.com
    web: https://cryptoms.fr/apropos
    twitter: https://twitter.com/_SteveD
    description: "Développeur & passionné des technologies Blockchain"
  marvin:
    name: Marvin Beaufort
    display_name: Marvin
    gravatar: d514306564cb7b586511e27c8aee0ade
    email: marvin.beaufort@orange.fr
    web: https://cryptoms.fr/apropos
    twitter: 
    description: "Diplômé de Master CCA, Auditeur/Collaborateur Comptable, passionné d'économie et de crypto-économie"

# Plugins
url: "https://cryptoms.fr"
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categorie/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

# Server config
include:
  - _headers

