# Site
name: "CryptoMS"
title: "Site internet spécialisé sur les technologies Blockchain & la Crypto-économie"
description: "Site internet spécialisé sur les technologies Blockchain & la Crypto-économie"
meta_description: "Site internet spécialisé sur les technologies Blockchain & la Crypto-économie"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
baseurl: ''
true_url: 'https://cryptoms.fr'
email: 'contact@cryptoms.fr'
google_analytics: 'UA-170496780-1'

# Authors
authors:
  steve:
    name: Steve Despres
    display_name: Steve
    gravatar: d514306564cb7b586511e27c8aee0ade
    email: steve.despres@protonmail.com
    web: https://cryptoms.fr/apropos
    twitter: https://twitter.com/steve_dsp
    description: "Développeur & passionné par les technologies Blockchain"
  marvin:
    name: Marvin Beaufort
    display_name: Marvin
    gravatar: a074b7d806a5b7ea1d60b06f6632622a
    email: marvin.beaufort@orange.fr
    web: https://cryptoms.fr/apropos
    twitter: 
    description: "Diplômé de Master CCA, Auditeur/Collaborateur Comptable, passionné d'économie et de Crypto-économie"

# Plugins
url: "https://cryptoms.fr"
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categorie/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

# Server config
include:
  - _headers

